### PR TITLE
Migrated to v2 embedding

### LINKED ISSUE #57: getExternalCacheDir() called on null when added to native android app
I am adding a flutter module using flutter_native_image as a dependency to a native android app. I get the error in the title when the android app is run. It seems like activity is always null which causes this issue.

I suspect this is something to do with v2 embedding and a migration of this plugin could possibly fix the issue. I'll open a PR if I manage to fix it.

### PR DESCRIPTION
**Pull request by adithyaxx**
Fixes #57

### CODE REVIEW

**Comment by btastic** [comment]
I don't really understand this PR. The code does not align well. Can you describe what you did? And what is v2 embedding?

**Comment by bosssanovar** [comment]
> 私はこのPRを本当に理解していません。コードはうまく整列しません。あなたがしたことを説明できますか？そして、v2埋め込みとは何ですか？

https://stackoverflow.com/questions/59988211/what-is-the-difference-between-flutter-android-embedding-v1-and-v2

**Comment by lts1610** [comment]
@btastic I have the same issue #57 

Please review this pull request and merge it.

**Comment by btastic** [comment]
I dont so much with flutter nowadays. I just merged. We can still go back if something fails.

**Pull request merged**
