### PR TITLE
Android X support

### PR DESCRIPTION
**Pull request by diegoveloper**
This change allows this package to be compatible with Android X dependencies

### CODE REVIEW

**Comment by diegoveloper** [comment]
Hi @btastic any news about this ?

**Comment by Eimji** [comment]
Please merge the PR (so that we can build with the latest dev version of Flutter).

**Comment by alexei-g-aloteq** [comment]
The module is broken now. Please merge this PR

**Comment by btastic** [comment]
Sorry, just merged it.

**Pull request merged**
